
  testmodule.handler.create_my_test_entity:
    class: Backend\Modules\TestModule\Domain\MyTestEntity\Command\CreateMyTestEntityHandler
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: command_handler, handles: Backend\Modules\TestModule\Domain\MyTestEntity\Command\CreateMyTestEntity }

  test.handler.delete_my_test_entity:
    class: Backend\Modules\TestModule\Domain\MyTestEntity\Command\DeleteMyTestEntityHandler
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: command_handler, handles: Backend\Modules\TestModule\Domain\MyTestEntity\Command\DeleteMyTestEntity }

  test.handler.update_my_test_entity:
    class: Backend\Modules\TestModule\Domain\MyTestEntity\Command\UpdateTestEntityHandler
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: command_handler, handles: Backend\Modules\TestModule\Domain\MyTestEntity\Command\UpdateMyTestEntity }
