language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1

script:
  - bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 --report=full "src"
  - vendor/bin/behat

before_script:
  - composer install


sudo: false
