services:
  module-generator_dumper:
    class: ModuleGenerator\CLI\Service\Generate\EchoDumper

  module-generator_settings_service:
    class: ModuleGenerator\CLI\Service\ModuleGenerator\Settings
    arguments:
      - '%kernel.root_dir%/cache/test/settings.yml'
