services:
  module-generator_dumper:
    class: ModuleGenerator\CLI\Service\Generate\ConsoleOutputDumper

  module-generator_appender:
    class: ModuleGenerator\CLI\Service\Generate\ConsoleOutputAppender
