#!/usr/bin/env php
<?php

$vendorDirectory = getVendorDirectory();

require_once $vendorDirectory . '/autoload.php';

use App\Kernel;
use App\Application;

$kernel = new Kernel('prod', false, $vendorDirectory);
$application = new Application($kernel);
$application->run();

function getVendorDirectory()
{
    if (is_file(__DIR__ . '/../vendor/autoload.php')) {
        return __DIR__ . '/../vendor';
    }

    return __DIR__ . '/../../..';
}
