imports:
  - { resource: ../src/CLI/Console/Generate/commands.yml }

services:
  module-generator_dumper:
    class: ModuleGenerator\CLI\Service\Generate\FileDumper
  module-generator_appender:
    class: ModuleGenerator\CLI\Service\Generate\FileAppender
